name: Deploy the backend
on:
    push:
        branches: [ main ]

jobs: 
    build: 
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout the code
              uses: actions/checkout@v2

            - name: Docker login
              uses: docker/login-action@v2
              with: 
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}}

            - name: Docker build and push
              uses: docker/build-push-action@v4
              with: 
                context: .
                file: ./docker/Dockerfile.backend
                push: true
                tags: mayk03jun/user-app-backend:${{github.sha}}

            - name: Deploy to my ec2 instance 
              uses: appleboy/ssh-action@v1.2.0
              with:
                host: 34.237.243.161
                username: ubuntu
                key: ${{ secrets.SSH_KEY }}
                port: 22
                script: |
                 ls
                 docker stop backend
                 docker run --name backend -p 8000:8000 -d mayk03jun/user-app-backend:${{github.sha}}

            




  